name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build-image:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t newsfetcher .

  upload-image:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: sina
          password: dop_v1_9154f42d658214290717b926fe8e188c96f69b5357d435fd7f6e34bca8d8f894

      - name: Verify local Docker images
        run: docker images

      - name: Push Docker image
        run: |
          docker tag newsfetcher registry.digitalocean.com/farabix/newsfetcher
          docker push registry.digitalocean.com/farabix/newsfetcher

  deploy-to-vps:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: upload-image

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 165.232.143.110
          username: root
          key: 5!1!n!@!Tofighi
          script: |
            docker pull registry.digitalocean.com/farabix/newsfetcher:latest
            docker stop newsfetcher || true
            docker rm newsfetcher || true
            docker run -d -p 8000:8000 --name newsfetcher registry.digitalocean.com/farabix/newsfetcher:latest
